<?php
	/**********************************
	 * A nyelvi fájlokban ugyanazok a
	 * változók vannak feltöltve az
	 * adott nyelvre szabott szöveggel.
	 * ********************************/

	$title = ["hu" => "Talpalatnyi Vadon", "en" => "Nature Rewilders"];

	/*menü*/
	$kapcsolat = ["hu" => "Kapcsolat", "en" => "Contact"];
	# rólunk => $t1...
	$tamogatas = ["hu" => "Támogatás", "en" => "Support us", "link" => "tamogatas"];
	$terepi = ["hu" => "Kalandok a vadonban", "en" => "Wild adventures", "link" => "terepi_programok"];

	/*csempék a nyitó oldalon*/
	$t1 = ["hu" => "Rólunk", "en" => "About us", "link" => "rolunk"];
	$t2 = ["hu" => "Küldetésünk és céljaink", "en" => "Mission & goals", "link" => "kuldetesunk_es_celjaink"];
	$t3 = ["hu" => "Tevékenységek", "en" => "Activities", "link" => "tevekenysegek"];
	$t4 = ["hu" => "Légy aktív", "en" => "Take&nbsp;an action", "link" => "legy_aktiv"];
	$t5 = ["hu" => "Vadon&nbsp;a kertben", "en" => "A&nbsp;wilder garden", "link" => "vadon_a_kertben"];
	$t6 = ["hu" => "Élőhelyek", "en" => "Habitats", "link" => "elohelyek"];
	$t7 = ["hu" => "Konfliktusok", "en" => "Conflicts", "link" => "konfliktusok"];
	$t8 = ["hu" => "Projektek", "en" => "Projects", "link" => "projektek"];

	/*navlist tömb*/
	$nav_list = [$t2, $t1, $t8, $t3, $terepi, $t5, $t4, $t7, $t6, $tamogatas];
?>
