			<div class="oldal-elem nyitolap">
				<h1 id="firstText"><?php print $focim[$la]; ?></h1>
				<h2 id="secondText"><?php print $alcim[$la]; ?></h2>
				<a class="downArrow" href="#tovabb" referrerpolicy="origin"><img class="arrowPict" src="../pict/downArrow.png" alt="Go down"></img></a>
			</div>
			<div id="tovabb">
				<div class="sor">
					<div class="nagy bal bg1"><a href="<?php print $t1["link"]?>"><h4><?php print $t1[$la]?></h4></a></div>
					<div class="kicsi">
						<div class="bg2"><a href="<?php print $t2["link"]?>"><h5><?php print $t2[$la]?></h5></a></div>
						<div class="bg3"><a href="<?php print $t3["link"]?>"><h5><?php print $t3[$la]?></h5></a></div>
					</div>
				</div>
				<div class="sor">
					<div class="kicsi dupla">
						<div class="bg4"><a href="<?php print $t4["link"]?>"><h5><?php print $t4[$la]?></h5></a></div>
						<div class="bg5"><a href="<?php print $t5["link"]?>"><h5><?php print $t5[$la]?></h5></a></div>
						<div class="bg6"><a href="<?php print $t6["link"]?>"><h5><?php print $t6[$la]?></h5></a></div>
						<div class="bg7"><a href="<?php print $t7["link"]?>"><h5><?php print $t7[$la]?></h5></a></div>
					</div>
					<div class="nagy jobb bg8"><a href="<?php print $t8["link"]?>"><h4><?php print $t8[$la]?></h4></a></div>
				</div>
			</div>
